#!/bin/sh
# 
# Plugin to monitor the number of channels to RabbitMQ
#
# Usage: Link or copy into /etc/munin/node.d/
#
# Parameters
#     env.conn_warn <warning channels>
#     env.conn_crit <critical channels>
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.

if [ "$1" = "autoconf" ]; then
  echo yes
  exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look. 

if [ "$1" = "config" ]; then
        CONN_WARN=${channel_warn:-500}
        CONN_CRIT=${channel_crit:-1000}

  # The host name this plugin is for. (Can be overridden to have
  # one machine answer for several)

  # The title of the graph
  echo 'graph_title RabbitMQ Channels'
  # Arguments to "rrdtool graph". In this case, tell it that the
  # lower limit of the graph is '0', and that 1k=1000 (not 1024)
  echo 'graph_args --base 1000 -l 0'
  # The Y-axis label
  echo 'graph_vlabel channels'
  # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 load instead of
  # 420 milliload)
  #echo 'graph_scale no'
  echo 'graph_category RabbitMQ'

  echo "channels.label Queues"
  echo "channels.warning $CONN_WARN"
  echo "channels.critical $CONN_CRIT"
  echo "channels.info Number of active channels"

  echo 'graph_info Shows the number of channels to RabbitMQ'
  # Last, if run with the "config"-parameter, quit here (don't
  # display any data)
  exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

echo "channels.value $(rabbitmqctl list_channels | grep -v "^Listing" | grep -v "done.$" | wc -l)"