#!/bin/sh
#
# Plugin to monitor the queues of a virtual_host in RabbitMQ
#
# Usage: Link or copy into /etc/munin/node.d/
#
# Parameters
#     env.vhost <AMQ virtual host>
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.

if [ "$1" = "autoconf" ]; then
  echo yes
  exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look.

VHOST=${vhost:-"/"}

if [ "$1" = "config" ]; then

  # The host name this plugin is for. (Can be overridden to have
  # one machine answer for several)

  # The title of the graph
  echo "graph_title RabbitMQ $VHOST Total Memory Usage"
  # Arguments to "rrdtool graph". In this case, tell it that the
  # lower limit of the graph is '0', and that 1k=1000 (not 1024)
  echo 'graph_args --base 1000 -l 0'
  # The Y-axis label
  echo 'graph_vlabel bytes'
  echo 'graph_category RabbitMQ'

  echo "bytes.label Bytes"

  echo 'graph_info Memory consumed by RabbitMQ in ErlangVM'
  # Last, if run with the "config"-parameter, quit here (don't
  # display any data)
  exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

echo "bytes.value $(rabbitmqctl status | egrep 'memory' | egrep -o '[0-9]+')"
